export enum NOTIFICATION_TYPE {
  EXTERNAL = 'external',
  INTERNAL = 'internal',
  BOTH = 'both',
}

export enum EXTERNAL_NOTIFICATION_METHOD {
  EMAIL = 'email',
  SMS = 'sms',
  BOTH = 'both',
}

export enum OTP_CODE_METHOD {
  EMAIL = 1,
  SMS = 2,
  GAUTH = 3,
}

export enum OTP_CODE_EVENT {
  SIGN_UP = 1,
  LOGIN_2FA = 2,
  FORGET_PASSWORD = 3,
  DEVICE_VERIFICATION = 4,
  PASSWORD_CHANGE = 5,
  DEVICE_VERIFICATION_ENABLE_DISABLE = 6,
  LOGIN_TWOFA_ENABLE_DISABLE = 7,
  LOGOUT_FROM_OTHER_DEVICE = 8,
}

export enum NOTIFICATION_STATUS {
  UNREAD = 0,
  READ = 1,
  CLEANED = 2,
}

export enum NOTIFICATION_EVENTS {
  NEW_DEVICE_VERIFICATION = 1,
  RESET_PASSWORD = 2,
  UPDATE_PASSWORD = 3,
  DEVICE_VERIFICATION_ENABLE_DISABLE = 4,
  LOGIN_TWOFA_ENABLE_DISABLE = 5,
  LOGOUT_FROM_OTHER_DEVICE = 6,
  LOGIN_FROM_NEW_IP = 7,
}

export const NOTIFICATION_EVENTS_ARR = [
  NOTIFICATION_EVENTS.NEW_DEVICE_VERIFICATION,
  NOTIFICATION_EVENTS.RESET_PASSWORD,
  NOTIFICATION_EVENTS.UPDATE_PASSWORD,
  NOTIFICATION_EVENTS.DEVICE_VERIFICATION_ENABLE_DISABLE,
  NOTIFICATION_EVENTS.LOGIN_TWOFA_ENABLE_DISABLE,
  NOTIFICATION_EVENTS.LOGOUT_FROM_OTHER_DEVICE,
  NOTIFICATION_EVENTS.LOGIN_FROM_NEW_IP,
];

export enum USER_NOTIFY_TYPE {
  REFETCH = 1,
  SHOW_ALERT = 2,
  SHOW_ALERT_N_REFETCH = 3,
}

export enum NOTIFICATION_ACTION {
  NEW_NOTIFICATION = 1,
  MARKED_AS_READ,
  CLEARED,
}
