//file types
export const FILE_TYPE_IMAGE = 'image';
export const FILE_TYPE_DOCUMENT = 'document';
export const FILE_TYPE_VIDEO = 'video';
export const FILE_TYPE_AUDIO = 'audio';
export const FILE_TYPE_3D = '_3d';
//

export const DEFAULT_MAX_DATA_SIZE_IN_BYTE = 10000000; // 10 mb
export const DEFAULT_MAX_FILE_UPLOAD_SIZE_IN_BYTE = 2000000; // 2 mb
export const DEFAULT_MAX_FILE_UPLOADS_AT_A_TIME = 10;

export const NEWEST_OR_RECENT_IN_MIN = 4320;

export const VERIFY_CODE_TYPE_AUTH = 1;

export const VERIFY_CODE_RESEND_TIME_IN_SEC = 60;

export const VERIFY_CODE_EXPIRATION_TIME_IN_MIN = 30;

export enum ACCOUNT_STATUS {
  PENDING = 1,
  SUCCESSFUL = 2,
}

export enum REG_TYPE {
  REGULAR = 1,
  GOOGLE = 2,
  APPLE = 3,
}

export enum GENDER {
  MALE = 1,
  FEMALE = 2,
  OTHERS = 3,
}

export enum VERIFICATION_CODE_METHOD {
  EMAIL = 1,
  SMS = 2,
  GAUTH = 3,
}

export enum SECURITY_RESET_METHOD {
  EMAIL = 'email',
  PHONE = 'phone',
  GAUTH = 'google2fa_secret',
}

export enum USER_CREDENTIALS {
  EMAIL = 'email',
  PHONE = 'phone',
  USERCODE = 'usercode',
}

export enum VERIFICATION_CODE_EVENT {
  SIGN_UP = 1,
  LOGIN_2FA = 2,
  FORGET_PASSWORD = 3,
  DEVICE_VERIFICATION = 4,
  PASSWORD_CHANGE = 5,
  RESET_SECURITY = 6,
  RESET_CREDENTIAL = 7,
  NEW_EMAIL_VERIFICATION = 8,
  NEW_PHONE_VERIFICATION = 9,
  USER_SECURITY_QUESTION_UPDATE = 10,
  DEVICE_VERIFICATION_ENABLE_DISABLE = 11,
  LOGIN_TWOFA_ENABLE_DISABLE = 12,
  RESET_ANTI_PHISHING_CODE = 13,
  LOGOUT_FROM_OTHER_DEVICE = 14,
  DISABLE_ACCOUNT = 15,
  USER_PAYMENT_METHOD_CRUD = 16,
}

// export enum DEVICE_TYPE {
//   WEB = 1,
//   MOBILE = 2,
// }

export enum DEVICE_TYPE {
  UNKNOWN = 'unknown',
  DESKTOP = 'desktop',
  SMARTPHONE = 'smartphone',
  MOBILE = 'mobile',
  TABLET = 'tablet',
  TELEVISION = 'television',
  SMART_DISPLAY = 'smart display',
  CAMERA = 'camera',
  CAR = 'car',
  CONSOLE = 'Console',
  PROTABLE_MEDIA_PLAYER = 'portable media player',
  PHABLET = 'phablet',
  WEARABLE = 'wearable',
  SMART_SPEAKER = 'smart speaker',
  FEATURE_PHONE = 'feature phone',
  PERIPHERAL = 'peripheral',
}

export enum SECURITY_RESET_STATUS {
  PROCESSING = 0,
  PENDING = 1,
  EXPIRED = 2,
  DONE = 3,
  FAILED = 4,
  REJECT = 5,
}

export enum SECURITY_RESET_STEPS {
  STEP_1_REQUESTED = 1,
  STEP_2_RESET_SUBMIT = 2,
  STEP_3_ANSWER_VERIFIED = 3,
}

export enum ACTIVITY_EVENT {
  LOGIN = 1,
  SECURITY = 2,
}

export enum ACTIVITY {
  //event login
  LOGIN = 1,
  LOGOUT = 2,

  //event security
  NEW_DEVICE_VERIFICATION = 3,
  RESET_PASSWORD = 4,
  CHANGE_PASSWORD = 5,
  RESET_SECURITY_METHOD = 6,
  RESET_CREDENTIAL = 7,
  RESET_ANTI_PHISHING_CODE = 8,
  DEVICE_VERIFICATION_ENABLE_DISABLE = 9,
  LOGIN_TWOFA_ENABLE_DISABLE = 10,
  USER_SECURITY_QUESTION_UPDATE = 11,
  KYC_VERIFICATION = 12,
  LOGOUT_FROM_OTHER_DEVICE = 13,
  DISABLE_ACCOUNT = 14,
}

export const MAXIMUM_RESET_VALUE_TRIES = 3;
export const MAXIMUM_ANSWER_TRIES = 3;

export const MAX_ACTIVE_NOTICE = 3;

// export const ACTIVITY_NOTIFICATION_MAP = {
//   [ACTIVITY.NEW_DEVICE_VERIFICATION]:
//     NOTIFICATION_EVENTS.NEW_DEVICE_VERIFICATION,
//   [ACTIVITY.RESET_PASSWORD]: NOTIFICATION_EVENTS.RESET_PASSWORD,
//   [ACTIVITY.CHANGE_PASSWORD]: NOTIFICATION_EVENTS.UPDATE_PASSWORD,
//   [ACTIVITY.DEVICE_VERIFICATION_ENABLE_DISABLE]:
//     NOTIFICATION_EVENTS.DEVICE_VERIFICATION_ENABLE_DISABLE,
//   [ACTIVITY.LOGIN_TWOFA_ENABLE_DISABLE]:
//     NOTIFICATION_EVENTS.LOGIN_TWOFA_ENABLE_DISABLE,
//   [ACTIVITY.LOGOUT_FROM_OTHER_DEVICE]:
//     NOTIFICATION_EVENTS.LOGOUT_FROM_OTHER_DEVICE,
// };
