import {
  REG_TYPE,
  USER_CREDENTIALS,
  VERIFICATION_CODE_METHOD,
  VERIFICATION_CODE_EVENT,
  DEVICE_TYPE,
} from './core_constant';

function __(str: string) {
  return str;
}

export const REG_TYPE_METHOD = {
  [REG_TYPE.REGULAR]: 'Email/Phone Password',
  [REG_TYPE.GOOGLE]: 'Google',
  [REG_TYPE.APPLE]: 'Apple',
};

export const Credential_CodeMethod = {
  [USER_CREDENTIALS.EMAIL]: VERIFICATION_CODE_METHOD.EMAIL,
  [USER_CREDENTIALS.PHONE]: VERIFICATION_CODE_METHOD.SMS,
};

export const Credential_CodeEvent_NewVerify = {
  [USER_CREDENTIALS.EMAIL]: VERIFICATION_CODE_EVENT.NEW_EMAIL_VERIFICATION,
  [USER_CREDENTIALS.PHONE]: VERIFICATION_CODE_EVENT.NEW_PHONE_VERIFICATION,
};

export const DEVICE_TYPES_FOR_MOBILE = [
  DEVICE_TYPE.FEATURE_PHONE,
  DEVICE_TYPE.PHABLET,
  DEVICE_TYPE.SMARTPHONE,
  DEVICE_TYPE.MOBILE,
];
