export const Country_Data: any = {
  AD: {
    iso3: 'AND',
    name: 'Andorra',
    capital: 'Andorra la Vella',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['ca'],
    phone_code: '+376',
  },
  AE: {
    iso3: 'ARE',
    name: 'United Arab Emirates',
    capital: 'Abu Dhabi',
    currencyCode: 'AED',
    currencyName: 'Dirham',
    lang: ['ar'],
    phone_code: '+971',
  },
  AF: {
    iso3: 'AFG',
    name: 'Afghanistan',
    capital: 'Kabul',
    currencyCode: 'AFN',
    currencyName: 'Afghani',
    lang: ['fa', 'ps'],
    phone_code: '+93',
  },
  AG: {
    iso3: 'ATG',
    name: 'Antigua and Barbuda',
    capital: "St. John's",
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1268',
  },
  AI: {
    iso3: 'AIA',
    name: 'Anguilla',
    capital: 'The Valley',
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1264',
  },
  AL: {
    iso3: 'ALB',
    name: 'Albania',
    capital: 'Tirana',
    currencyCode: 'ALL',
    currencyName: 'Lek',
    lang: ['sq'],
    phone_code: '+355',
  },
  AM: {
    iso3: 'ARM',
    name: 'Armenia',
    capital: 'Yerevan',
    currencyCode: 'AMD',
    currencyName: 'Dram',
    lang: ['hy'],
    phone_code: '+374',
  },
  AO: {
    iso3: 'AGO',
    name: 'Angola',
    capital: 'Luanda',
    currencyCode: 'AOA',
    currencyName: 'Kwanza',
    lang: ['pt'],
    phone_code: '+244',
  },
  AQ: {
    iso3: 'ATA',
    name: 'Antarctica',
    capital: '',
    currencyCode: '',
    currencyName: '',
    lang: ['en', 'es', 'fr', 'ru'],
    phone_code: '+672',
  },
  AR: {
    iso3: 'ARG',
    name: 'Argentina',
    capital: 'Buenos Aires',
    currencyCode: 'ARS',
    currencyName: 'Peso',
    lang: ['es'],
    phone_code: '+54',
  },
  AS: {
    iso3: 'ASM',
    name: 'American Samoa',
    capital: 'Pago Pago',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en', 'sm'],
    phone_code: '+1684',
  },
  AT: {
    iso3: 'AUT',
    name: 'Austria',
    capital: 'Vienna',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['de'],
    phone_code: '+43',
  },
  AU: {
    iso3: 'AUS',
    name: 'Australia',
    capital: 'Canberra',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+61',
  },
  AW: {
    iso3: 'ABW',
    name: 'Aruba',
    capital: 'Oranjestad',
    currencyCode: 'AWG',
    currencyName: 'Guilder',
    lang: ['nl', 'pap'],
    phone_code: '+297',
  },
  AX: {
    iso3: 'ALA',
    name: 'Aland Islands',
    capital: 'Mariehamn',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['sv'],
    phone_code: '+358',
  },
  AZ: {
    iso3: 'AZE',
    name: 'Azerbaijan',
    capital: 'Baku',
    currencyCode: 'AZN',
    currencyName: 'Manat',
    lang: ['az'],
    phone_code: '+994',
  },
  BA: {
    iso3: 'BIH',
    name: 'Bosnia and Herzegovina',
    capital: 'Sarajevo',
    currencyCode: 'BAM',
    currencyName: 'Marka',
    lang: ['bs', 'hr', 'sr'],
    phone_code: '+387',
  },
  BB: {
    iso3: 'BRB',
    name: 'Barbados',
    capital: 'Bridgetown',
    currencyCode: 'BBD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1246',
  },
  BD: {
    iso3: 'BGD',
    name: 'Bangladesh',
    capital: 'Dhaka',
    currencyCode: 'BDT',
    currencyName: 'Taka',
    lang: ['bn'],
    phone_code: '+880',
  },
  BE: {
    iso3: 'BEL',
    name: 'Belgium',
    capital: 'Brussels',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['nl', 'fr', 'de'],
    phone_code: '+32',
  },
  BF: {
    iso3: 'BFA',
    name: 'Burkina Faso',
    capital: 'Ouagadougou',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+226',
  },
  BG: {
    iso3: 'BGR',
    name: 'Bulgaria',
    capital: 'Sofia',
    currencyCode: 'BGN',
    currencyName: 'Lev',
    lang: ['bg'],
    phone_code: '+359',
  },
  BH: {
    iso3: 'BHR',
    name: 'Bahrain',
    capital: 'Manama',
    currencyCode: 'BHD',
    currencyName: 'Dinar',
    lang: ['ar'],
    phone_code: '+973',
  },
  BI: {
    iso3: 'BDI',
    name: 'Burundi',
    capital: 'Bujumbura',
    currencyCode: 'BIF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+257',
  },
  BJ: {
    iso3: 'BEN',
    name: 'Benin',
    capital: 'Porto-Novo',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+229',
  },
  BL: {
    iso3: 'BLM',
    name: 'Saint Barthelemy',
    capital: 'Gustavia',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+590',
  },
  BM: {
    iso3: 'BMU',
    name: 'Bermuda',
    capital: 'Hamilton',
    currencyCode: 'BMD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1441',
  },
  BN: {
    iso3: 'BRN',
    name: 'Brunei',
    capital: 'Bandar Seri Begawan',
    currencyCode: 'BND',
    currencyName: 'Dollar',
    lang: ['ms'],
    phone_code: '+673',
  },
  BO: {
    iso3: 'BOL',
    name: 'Bolivia',
    capital: 'Sucre',
    currencyCode: 'BOB',
    currencyName: 'Boliviano',
    lang: ['es', 'qu', 'ay'],
    phone_code: '+591',
  },
  BQ: {
    iso3: 'BES',
    name: 'Bonaire, Saint Eustatius and Saba',
    capital: '',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['nl'],
    phone_code: '+599',
  },
  BR: {
    iso3: 'BRA',
    name: 'Brazil',
    capital: 'Brasilia',
    currencyCode: 'BRL',
    currencyName: 'Real',
    lang: ['pt'],
    phone_code: '+55',
  },
  BS: {
    iso3: 'BHS',
    name: 'Bahamas',
    capital: 'Nassau',
    currencyCode: 'BSD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1242',
  },
  BT: {
    iso3: 'BTN',
    name: 'Bhutan',
    capital: 'Thimphu',
    currencyCode: 'BTN',
    currencyName: 'Ngultrum',
    lang: ['dz'],
    phone_code: '+975',
  },
  BV: {
    iso3: 'BVT',
    name: 'Bouvet Island',
    capital: '',
    currencyCode: 'NOK',
    currencyName: 'Krone',
    lang: ['no'],
    phone_code: '+47',
  },
  BW: {
    iso3: 'BWA',
    name: 'Botswana',
    capital: 'Gaborone',
    currencyCode: 'BWP',
    currencyName: 'Pula',
    lang: ['en', 'tn'],
    phone_code: '+267',
  },
  BY: {
    iso3: 'BLR',
    name: 'Belarus',
    capital: 'Minsk',
    currencyCode: 'BYR',
    currencyName: 'Ruble',
    lang: ['be', 'ru'],
    phone_code: '+375',
  },
  BZ: {
    iso3: 'BLZ',
    name: 'Belize',
    capital: 'Belmopan',
    currencyCode: 'BZD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+501',
  },
  CA: {
    iso3: 'CAN',
    name: 'Canada',
    capital: 'Ottawa',
    currencyCode: 'CAD',
    currencyName: 'Dollar',
    lang: ['en', 'fr'],
    phone_code: '+1',
  },
  CC: {
    iso3: 'CCK',
    name: 'Cocos Islands',
    capital: 'West Island',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+61',
  },
  CD: {
    iso3: 'COD',
    name: 'Democratic Republic of the Congo',
    capital: 'Kinshasa',
    currencyCode: 'CDF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+243',
  },
  CF: {
    iso3: 'CAF',
    name: 'Central African Republic',
    capital: 'Bangui',
    currencyCode: 'XAF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+236',
  },
  CG: {
    iso3: 'COG',
    name: 'Republic of the Congo',
    capital: 'Brazzaville',
    currencyCode: 'XAF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+242',
  },
  CH: {
    iso3: 'CHE',
    name: 'Switzerland',
    capital: 'Berne',
    currencyCode: 'CHF',
    currencyName: 'Franc',
    lang: ['de', 'fr', 'it', 'rm'],
    phone_code: '+41',
  },
  CI: {
    iso3: 'CIV',
    name: 'Ivory Coast',
    capital: 'Yamoussoukro',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+225',
  },
  CK: {
    iso3: 'COK',
    name: 'Cook Islands',
    capital: 'Avarua',
    currencyCode: 'NZD',
    currencyName: 'Dollar',
    lang: ['en', 'rar'],
    phone_code: '+682',
  },
  CL: {
    iso3: 'CHL',
    name: 'Chile',
    capital: 'Santiago',
    currencyCode: 'CLP',
    currencyName: 'Peso',
    lang: ['es'],
    phone_code: '+56',
  },
  CM: {
    iso3: 'CMR',
    name: 'Cameroon',
    capital: 'Yaounde',
    currencyCode: 'XAF',
    currencyName: 'Franc',
    lang: ['fr', 'en'],
    phone_code: '+237',
  },
  CN: {
    iso3: 'CHN',
    name: 'China',
    capital: 'Beijing',
    currencyCode: 'CNY',
    currencyName: 'Yuan Renminbi',
    lang: ['zh'],
    phone_code: '+86',
  },
  CO: {
    iso3: 'COL',
    name: 'Colombia',
    capital: 'Bogota',
    currencyCode: 'COP',
    currencyName: 'Peso',
    lang: ['es'],
    phone_code: '+57',
  },
  CR: {
    iso3: 'CRI',
    name: 'Costa Rica',
    capital: 'San Jose',
    currencyCode: 'CRC',
    currencyName: 'Colon',
    lang: ['es'],
    phone_code: '+506',
  },
  CU: {
    iso3: 'CUB',
    name: 'Cuba',
    capital: 'Havana',
    currencyCode: 'CUP',
    currencyName: 'Peso',
    lang: ['es'],
    phone_code: '+53',
  },
  CV: {
    iso3: 'CPV',
    name: 'Cape Verde',
    capital: 'Praia',
    currencyCode: 'CVE',
    currencyName: 'Escudo',
    lang: ['pt'],
    phone_code: '+238',
  },
  CW: {
    iso3: 'CUW',
    name: 'Curacao',
    capital: 'Willemstad',
    currencyCode: 'ANG',
    currencyName: 'Guilder',
    lang: ['nl', 'en'],
    phone_code: '+599',
  },
  CX: {
    iso3: 'CXR',
    name: 'Christmas Island',
    capital: 'Flying Fish Cove',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+61',
  },
  CY: {
    iso3: 'CYP',
    name: 'Cyprus',
    capital: 'Nicosia',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['el', 'tr'],
    phone_code: '+357',
  },
  CZ: {
    iso3: 'CZE',
    name: 'Czech Republic',
    capital: 'Prague',
    currencyCode: 'CZK',
    currencyName: 'Koruna',
    lang: ['cs'],
    phone_code: '+420',
  },
  DE: {
    iso3: 'DEU',
    name: 'Germany',
    capital: 'Berlin',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['de'],
    phone_code: '+49',
  },
  DJ: {
    iso3: 'DJI',
    name: 'Djibouti',
    capital: 'Djibouti',
    currencyCode: 'DJF',
    currencyName: 'Franc',
    lang: ['fr', 'ar'],
    phone_code: '+253',
  },
  DK: {
    iso3: 'DNK',
    name: 'Denmark',
    capital: 'Copenhagen',
    currencyCode: 'DKK',
    currencyName: 'Krone',
    lang: ['da'],
    phone_code: '+45',
  },
  DM: {
    iso3: 'DMA',
    name: 'Dominica',
    capital: 'Roseau',
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1767',
  },
  DO: {
    iso3: 'DOM',
    name: 'Dominican Republic',
    capital: 'Santo Domingo',
    currencyCode: 'DOP',
    currencyName: 'Peso',
    lang: ['es'],
    phone_code: '+1849',
  },
  DZ: {
    iso3: 'DZA',
    name: 'Algeria',
    capital: 'Algiers',
    currencyCode: 'DZD',
    currencyName: 'Dinar',
    lang: ['ar', 'ber'],
    phone_code: '+213',
  },
  EC: {
    iso3: 'ECU',
    name: 'Ecuador',
    capital: 'Quito',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['es'],
    phone_code: '+593',
  },
  EE: {
    iso3: 'EST',
    name: 'Estonia',
    capital: 'Tallinn',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['et'],
    phone_code: '+372',
  },
  EG: {
    iso3: 'EGY',
    name: 'Egypt',
    capital: 'Cairo',
    currencyCode: 'EGP',
    currencyName: 'Pound',
    lang: ['ar'],
    phone_code: '+20',
  },
  EH: {
    iso3: 'ESH',
    name: 'Western Sahara',
    capital: 'El-Aaiun',
    currencyCode: 'MAD',
    currencyName: 'Dirham',
    lang: ['ar', 'es', 'fr'],
    phone_code: '+212',
  },
  ER: {
    iso3: 'ERI',
    name: 'Eritrea',
    capital: 'Asmara',
    currencyCode: 'ERN',
    currencyName: 'Nakfa',
    lang: ['ti', 'ar', 'en'],
    phone_code: '+291',
  },
  ES: {
    iso3: 'ESP',
    name: 'Spain',
    capital: 'Madrid',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['es'],
    phone_code: '+34',
  },
  ET: {
    iso3: 'ETH',
    name: 'Ethiopia',
    capital: 'Addis Ababa',
    currencyCode: 'ETB',
    currencyName: 'Birr',
    lang: ['am', 'om'],
    phone_code: '+251',
  },
  FI: {
    iso3: 'FIN',
    name: 'Finland',
    capital: 'Helsinki',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fi', 'sv', 'se'],
    phone_code: '+358',
  },
  FJ: {
    iso3: 'FJI',
    name: 'Fiji',
    capital: 'Suva',
    currencyCode: 'FJD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+679',
  },
  FK: {
    iso3: 'FLK',
    name: 'Falkland Islands',
    capital: 'Stanley',
    currencyCode: 'FKP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+500',
  },
  FM: {
    iso3: 'FSM',
    name: 'Micronesia',
    capital: 'Palikir',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+691',
  },
  FO: {
    iso3: 'FRO',
    name: 'Faroe Islands',
    capital: 'Torshavn',
    currencyCode: 'DKK',
    currencyName: 'Krone',
    lang: ['fo'],
    phone_code: '+298',
  },
  FR: {
    iso3: 'FRA',
    name: 'France',
    capital: 'Paris',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+33',
  },
  GA: {
    iso3: 'GAB',
    name: 'Gabon',
    capital: 'Libreville',
    currencyCode: 'XAF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+241',
  },
  GB: {
    iso3: 'GBR',
    name: 'United Kingdom',
    capital: 'London',
    currencyCode: 'GBP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+44',
  },
  GD: {
    iso3: 'GRD',
    name: 'Grenada',
    capital: "St. George's",
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1473',
  },
  GE: {
    iso3: 'GEO',
    name: 'Georgia',
    capital: 'Tbilisi',
    currencyCode: 'GEL',
    currencyName: 'Lari',
    lang: ['ka'],
    phone_code: '+995',
  },
  GF: {
    iso3: 'GUF',
    name: 'French Guiana',
    capital: 'Cayenne',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+594',
  },
  GG: {
    iso3: 'GGY',
    name: 'Guernsey',
    capital: 'St Peter Port',
    currencyCode: 'GBP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+44',
  },
  GH: {
    iso3: 'GHA',
    name: 'Ghana',
    capital: 'Accra',
    currencyCode: 'GHS',
    currencyName: 'Cedi',
    lang: ['en'],
    phone_code: '+233',
  },
  GI: {
    iso3: 'GIB',
    name: 'Gibraltar',
    capital: 'Gibraltar',
    currencyCode: 'GIP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+350',
  },
  GL: {
    iso3: 'GRL',
    name: 'Greenland',
    capital: 'Nuuk',
    currencyCode: 'DKK',
    currencyName: 'Krone',
    lang: ['kl', 'da'],
    phone_code: '+299',
  },
  GM: {
    iso3: 'GMB',
    name: 'Gambia',
    capital: 'Banjul',
    currencyCode: 'GMD',
    currencyName: 'Dalasi',
    lang: ['en'],
    phone_code: '+220',
  },
  GN: {
    iso3: 'GIN',
    name: 'Guinea',
    capital: 'Conakry',
    currencyCode: 'GNF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+224',
  },
  GP: {
    iso3: 'GLP',
    name: 'Guadeloupe',
    capital: 'Basse-Terre',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+590',
  },
  GQ: {
    iso3: 'GNQ',
    name: 'Equatorial Guinea',
    capital: 'Malabo',
    currencyCode: 'XAF',
    currencyName: 'Franc',
    lang: ['es'],
    phone_code: '+240',
  },
  GR: {
    iso3: 'GRC',
    name: 'Greece',
    capital: 'Athens',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['el'],
    phone_code: '+30',
  },
  GS: {
    iso3: 'SGS',
    name: 'South Georgia and the South Sandwich Islands',
    capital: 'Grytviken',
    currencyCode: 'GBP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+500',
  },
  GT: {
    iso3: 'GTM',
    name: 'Guatemala',
    capital: 'Guatemala City',
    currencyCode: 'GTQ',
    currencyName: 'Quetzal',
    lang: ['es'],
    phone_code: '+502',
  },
  GU: {
    iso3: 'GUM',
    name: 'Guam',
    capital: 'Hagatna',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en', 'ch'],
    phone_code: '+1671',
  },
  GW: {
    iso3: 'GNB',
    name: 'Guinea-Bissau',
    capital: 'Bissau',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['pt'],
    phone_code: '+245',
  },
  GY: {
    iso3: 'GUY',
    name: 'Guyana',
    capital: 'Georgetown',
    currencyCode: 'GYD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+595',
  },
  HK: {
    iso3: 'HKG',
    name: 'Hong Kong',
    capital: 'Hong Kong',
    currencyCode: 'HKD',
    currencyName: 'Dollar',
    lang: ['zh', 'en'],
    phone_code: '+852',
  },
  HM: {
    iso3: 'HMD',
    name: 'Heard Island and McDonald Islands',
    capital: '',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '',
  },
  HN: {
    iso3: 'HND',
    name: 'Honduras',
    capital: 'Tegucigalpa',
    currencyCode: 'HNL',
    currencyName: 'Lempira',
    lang: ['es'],
    phone_code: '+504',
  },
  HR: {
    iso3: 'HRV',
    name: 'Croatia',
    capital: 'Zagreb',
    currencyCode: 'HRK',
    currencyName: 'Kuna',
    lang: ['hr'],
    phone_code: '+385',
  },
  HT: {
    iso3: 'HTI',
    name: 'Haiti',
    capital: 'Port-au-Prince',
    currencyCode: 'HTG',
    currencyName: 'Gourde',
    lang: ['fr', 'ht'],
    phone_code: '+509',
  },
  HU: {
    iso3: 'HUN',
    name: 'Hungary',
    capital: 'Budapest',
    currencyCode: 'HUF',
    currencyName: 'Forint',
    lang: ['hu'],
    phone_code: '+36',
  },
  ID: {
    iso3: 'IDN',
    name: 'Indonesia',
    capital: 'Jakarta',
    currencyCode: 'IDR',
    currencyName: 'Rupiah',
    lang: ['id'],
    phone_code: '+62',
  },
  IE: {
    iso3: 'IRL',
    name: 'Ireland',
    capital: 'Dublin',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['en', 'ga'],
    phone_code: '+353',
  },
  IL: {
    iso3: 'ISR',
    name: 'Israel',
    capital: 'Jerusalem',
    currencyCode: 'ILS',
    currencyName: 'Shekel',
    lang: ['he'],
    phone_code: '+972',
  },
  IM: {
    iso3: 'IMN',
    name: 'Isle of Man',
    capital: 'Douglas, Isle of Man',
    currencyCode: 'GBP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+44',
  },
  IN: {
    iso3: 'IND',
    name: 'India',
    capital: 'New Delhi',
    currencyCode: 'INR',
    currencyName: 'Rupee',
    lang: ['hi', 'en'],
    phone_code: '+91',
  },
  IO: {
    iso3: 'IOT',
    name: 'British Indian Ocean Territory',
    capital: 'Diego Garcia',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+246',
  },
  IQ: {
    iso3: 'IRQ',
    name: 'Iraq',
    capital: 'Baghdad',
    currencyCode: 'IQD',
    currencyName: 'Dinar',
    lang: ['ar', 'ku'],
    phone_code: '+964',
  },
  IR: {
    iso3: 'IRN',
    name: 'Iran',
    capital: 'Tehran',
    currencyCode: 'IRR',
    currencyName: 'Rial',
    lang: ['fa'],
    phone_code: '+98',
  },
  IS: {
    iso3: 'ISL',
    name: 'Iceland',
    capital: 'Reykjavik',
    currencyCode: 'ISK',
    currencyName: 'Krona',
    lang: ['is'],
    phone_code: '+354',
  },
  IT: {
    iso3: 'ITA',
    name: 'Italy',
    capital: 'Rome',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['it'],
    phone_code: '+39',
  },
  JE: {
    iso3: 'JEY',
    name: 'Jersey',
    capital: 'Saint Helier',
    currencyCode: 'GBP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+44',
  },
  JM: {
    iso3: 'JAM',
    name: 'Jamaica',
    capital: 'Kingston',
    currencyCode: 'JMD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1876',
  },
  JO: {
    iso3: 'JOR',
    name: 'Jordan',
    capital: 'Amman',
    currencyCode: 'JOD',
    currencyName: 'Dinar',
    lang: ['ar'],
    phone_code: '+962',
  },
  JP: {
    iso3: 'JPN',
    name: 'Japan',
    capital: 'Tokyo',
    currencyCode: 'JPY',
    currencyName: 'Yen',
    lang: ['ja'],
    phone_code: '+81',
  },
  KE: {
    iso3: 'KEN',
    name: 'Kenya',
    capital: 'Nairobi',
    currencyCode: 'KES',
    currencyName: 'Shilling',
    lang: ['sw', 'en'],
    phone_code: '+254',
  },
  KG: {
    iso3: 'KGZ',
    name: 'Kyrgyzstan',
    capital: 'Bishkek',
    currencyCode: 'KGS',
    currencyName: 'Som',
    lang: ['ky', 'ru'],
    phone_code: '+996',
  },
  KH: {
    iso3: 'KHM',
    name: 'Cambodia',
    capital: 'Phnom Penh',
    currencyCode: 'KHR',
    currencyName: 'Riels',
    lang: ['km'],
    phone_code: '+855',
  },
  KI: {
    iso3: 'KIR',
    name: 'Kiribati',
    capital: 'Tarawa',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+686',
  },
  KM: {
    iso3: 'COM',
    name: 'Comoros',
    capital: 'Moroni',
    currencyCode: 'KMF',
    currencyName: 'Franc',
    lang: ['bnt', 'ar', 'fr'],
    phone_code: '+269',
  },
  KN: {
    iso3: 'KNA',
    name: 'Saint Kitts and Nevis',
    capital: 'Basseterre',
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1869',
  },
  KP: {
    iso3: 'PRK',
    name: 'North Korea',
    capital: 'Pyongyang',
    currencyCode: 'KPW',
    currencyName: 'Won',
    lang: ['ko'],
    phone_code: '+850',
  },
  KR: {
    iso3: 'KOR',
    name: 'South Korea',
    capital: 'Seoul',
    currencyCode: 'KRW',
    currencyName: 'Won',
    lang: ['ko'],
    phone_code: '+82',
  },
  XK: {
    iso3: 'XKX',
    name: 'Kosovo',
    capital: 'Pristina',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['sq', 'sr'],
    phone_code: '+383',
  },
  KW: {
    iso3: 'KWT',
    name: 'Kuwait',
    capital: 'Kuwait City',
    currencyCode: 'KWD',
    currencyName: 'Dinar',
    lang: ['ar'],
    phone_code: '+965',
  },
  KY: {
    iso3: 'CYM',
    name: 'Cayman Islands',
    capital: 'George Town',
    currencyCode: 'KYD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+ 345',
  },
  KZ: {
    iso3: 'KAZ',
    name: 'Kazakhstan',
    capital: 'Astana',
    currencyCode: 'KZT',
    currencyName: 'Tenge',
    lang: ['kk', 'ru'],
    phone_code: '+77',
  },
  LA: {
    iso3: 'LAO',
    name: 'Laos',
    capital: 'Vientiane',
    currencyCode: 'LAK',
    currencyName: 'Kip',
    lang: ['lo'],
    phone_code: '+856',
  },
  LB: {
    iso3: 'LBN',
    name: 'Lebanon',
    capital: 'Beirut',
    currencyCode: 'LBP',
    currencyName: 'Pound',
    lang: ['ar', 'fr'],
    phone_code: '+961',
  },
  LC: {
    iso3: 'LCA',
    name: 'Saint Lucia',
    capital: 'Castries',
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1758',
  },
  LI: {
    iso3: 'LIE',
    name: 'Liechtenstein',
    capital: 'Vaduz',
    currencyCode: 'CHF',
    currencyName: 'Franc',
    lang: ['de'],
    phone_code: '+423',
  },
  LK: {
    iso3: 'LKA',
    name: 'Sri Lanka',
    capital: 'Colombo',
    currencyCode: 'LKR',
    currencyName: 'Rupee',
    lang: ['si', 'ta'],
    phone_code: '+94',
  },
  LR: {
    iso3: 'LBR',
    name: 'Liberia',
    capital: 'Monrovia',
    currencyCode: 'LRD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+231',
  },
  LS: {
    iso3: 'LSO',
    name: 'Lesotho',
    capital: 'Maseru',
    currencyCode: 'LSL',
    currencyName: 'Loti',
    lang: ['en', 'st'],
    phone_code: '+266',
  },
  LT: {
    iso3: 'LTU',
    name: 'Lithuania',
    capital: 'Vilnius',
    currencyCode: 'LTL',
    currencyName: 'Litas',
    lang: ['lt'],
    phone_code: '+370',
  },
  LU: {
    iso3: 'LUX',
    name: 'Luxembourg',
    capital: 'Luxembourg',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['lb', 'fr', 'de'],
    phone_code: '+352',
  },
  LV: {
    iso3: 'LVA',
    name: 'Latvia',
    capital: 'Riga',
    currencyCode: 'LVL',
    currencyName: 'Lat',
    lang: ['lv'],
    phone_code: '+371',
  },
  LY: {
    iso3: 'LBY',
    name: 'Libya',
    capital: 'Tripolis',
    currencyCode: 'LYD',
    currencyName: 'Dinar',
    lang: ['ar', 'ber'],
    phone_code: '+218',
  },
  MA: {
    iso3: 'MAR',
    name: 'Morocco',
    capital: 'Rabat',
    currencyCode: 'MAD',
    currencyName: 'Dirham',
    lang: ['ar', 'ber'],
    phone_code: '+212',
  },
  MC: {
    iso3: 'MCO',
    name: 'Monaco',
    capital: 'Monaco',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+377',
  },
  MD: {
    iso3: 'MDA',
    name: 'Moldova',
    capital: 'Chisinau',
    currencyCode: 'MDL',
    currencyName: 'Leu',
    lang: ['ru', 'uk', 'ro'],
    phone_code: '+373',
  },
  ME: {
    iso3: 'MNE',
    name: 'Montenegro',
    capital: 'Podgorica',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['sr', 'sh'],
    phone_code: '+382',
  },
  MF: {
    iso3: 'MAF',
    name: 'Saint Martin',
    capital: 'Marigot',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+590',
  },
  MG: {
    iso3: 'MDG',
    name: 'Madagascar',
    capital: 'Antananarivo',
    currencyCode: 'MGA',
    currencyName: 'Ariary',
    lang: ['mg', 'fr'],
    phone_code: '+261',
  },
  MH: {
    iso3: 'MHL',
    name: 'Marshall Islands',
    capital: 'Majuro',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en', 'mh'],
    phone_code: '+692',
  },
  MK: {
    iso3: 'MKD',
    name: 'Macedonia',
    capital: 'Skopje',
    currencyCode: 'MKD',
    currencyName: 'Denar',
    lang: ['mk'],
    phone_code: '+389',
  },
  ML: {
    iso3: 'MLI',
    name: 'Mali',
    capital: 'Bamako',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+223',
  },
  MM: {
    iso3: 'MMR',
    name: 'Myanmar',
    capital: 'Nay Pyi Taw',
    currencyCode: 'MMK',
    currencyName: 'Kyat',
    lang: ['my'],
    phone_code: '+95',
  },
  MN: {
    iso3: 'MNG',
    name: 'Mongolia',
    capital: 'Ulan Bator',
    currencyCode: 'MNT',
    currencyName: 'Tugrik',
    lang: ['mn'],
    phone_code: '+976',
  },
  MO: {
    iso3: 'MAC',
    name: 'Macao',
    capital: 'Macao',
    currencyCode: 'MOP',
    currencyName: 'Pataca',
    lang: ['zh', 'pt'],
    phone_code: '+853',
  },
  MP: {
    iso3: 'MNP',
    name: 'Northern Mariana Islands',
    capital: 'Saipan',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['ch'],
    phone_code: '+1670',
  },
  MQ: {
    iso3: 'MTQ',
    name: 'Martinique',
    capital: 'Fort-de-France',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+596',
  },
  MR: {
    iso3: 'MRT',
    name: 'Mauritania',
    capital: 'Nouakchott',
    currencyCode: 'MRO',
    currencyName: 'Ouguiya',
    lang: ['ar', 'fr'],
    phone_code: '+222',
  },
  MS: {
    iso3: 'MSR',
    name: 'Montserrat',
    capital: 'Plymouth',
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1664',
  },
  MT: {
    iso3: 'MLT',
    name: 'Malta',
    capital: 'Valletta',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['mt', 'en'],
    phone_code: '+356',
  },
  MU: {
    iso3: 'MUS',
    name: 'Mauritius',
    capital: 'Port Louis',
    currencyCode: 'MUR',
    currencyName: 'Rupee',
    lang: ['mfe', 'fr', 'en'],
    phone_code: '+230',
  },
  MV: {
    iso3: 'MDV',
    name: 'Maldives',
    capital: 'Male',
    currencyCode: 'MVR',
    currencyName: 'Rufiyaa',
    lang: ['dv'],
    phone_code: '+960',
  },
  MW: {
    iso3: 'MWI',
    name: 'Malawi',
    capital: 'Lilongwe',
    currencyCode: 'MWK',
    currencyName: 'Kwacha',
    lang: ['en', 'ny'],
    phone_code: '+265',
  },
  MX: {
    iso3: 'MEX',
    name: 'Mexico',
    capital: 'Mexico City',
    currencyCode: 'MXN',
    currencyName: 'Peso',
    lang: ['es'],
    phone_code: '+52',
  },
  MY: {
    iso3: 'MYS',
    name: 'Malaysia',
    capital: 'Kuala Lumpur',
    currencyCode: 'MYR',
    currencyName: 'Ringgit',
    lang: ['ms'],
    phone_code: '+60',
  },
  MZ: {
    iso3: 'MOZ',
    name: 'Mozambique',
    capital: 'Maputo',
    currencyCode: 'MZN',
    currencyName: 'Metical',
    lang: ['pt'],
    phone_code: '+258',
  },
  NA: {
    iso3: 'NAM',
    name: 'Namibia',
    capital: 'Windhoek',
    currencyCode: 'NAD',
    currencyName: 'Dollar',
    lang: ['en', 'sf', 'de'],
    phone_code: '+264',
  },
  NC: {
    iso3: 'NCL',
    name: 'New Caledonia',
    capital: 'Noumea',
    currencyCode: 'XPF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+687',
  },
  NE: {
    iso3: 'NER',
    name: 'Niger',
    capital: 'Niamey',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+227',
  },
  NF: {
    iso3: 'NFK',
    name: 'Norfolk Island',
    capital: 'Kingston',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['en', 'pih'],
    phone_code: '+672',
  },
  NG: {
    iso3: 'NGA',
    name: 'Nigeria',
    capital: 'Abuja',
    currencyCode: 'NGN',
    currencyName: 'Naira',
    lang: ['en'],
    phone_code: '+234',
  },
  NI: {
    iso3: 'NIC',
    name: 'Nicaragua',
    capital: 'Managua',
    currencyCode: 'NIO',
    currencyName: 'Cordoba',
    lang: ['es'],
    phone_code: '+505',
  },
  NL: {
    iso3: 'NLD',
    name: 'Netherlands',
    capital: 'Amsterdam',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['nl'],
    phone_code: '+31',
  },
  NO: {
    iso3: 'NOR',
    name: 'Norway',
    capital: 'Oslo',
    currencyCode: 'NOK',
    currencyName: 'Krone',
    lang: ['nb', 'nn', 'no'],
    phone_code: '+47',
  },
  NP: {
    iso3: 'NPL',
    name: 'Nepal',
    capital: 'Kathmandu',
    currencyCode: 'NPR',
    currencyName: 'Rupee',
    lang: ['ne'],
    phone_code: '+977',
  },
  NR: {
    iso3: 'NRU',
    name: 'Nauru',
    capital: 'Yaren',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['na', 'en'],
    phone_code: '+674',
  },
  NU: {
    iso3: 'NIU',
    name: 'Niue',
    capital: 'Alofi',
    currencyCode: 'NZD',
    currencyName: 'Dollar',
    lang: ['niu', 'en'],
    phone_code: '+683',
  },
  NZ: {
    iso3: 'NZL',
    name: 'New Zealand',
    capital: 'Wellington',
    currencyCode: 'NZD',
    currencyName: 'Dollar',
    lang: ['mi', 'en'],
    phone_code: '+64',
  },
  OM: {
    iso3: 'OMN',
    name: 'Oman',
    capital: 'Muscat',
    currencyCode: 'OMR',
    currencyName: 'Rial',
    lang: ['ar'],
    phone_code: '+968',
  },
  PA: {
    iso3: 'PAN',
    name: 'Panama',
    capital: 'Panama City',
    currencyCode: 'PAB',
    currencyName: 'Balboa',
    lang: ['es'],
    phone_code: '+507',
  },
  PE: {
    iso3: 'PER',
    name: 'Peru',
    capital: 'Lima',
    currencyCode: 'PEN',
    currencyName: 'Sol',
    lang: ['es'],
    phone_code: '+51',
  },
  PF: {
    iso3: 'PYF',
    name: 'French Polynesia',
    capital: 'Papeete',
    currencyCode: 'XPF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+689',
  },
  PG: {
    iso3: 'PNG',
    name: 'Papua New Guinea',
    capital: 'Port Moresby',
    currencyCode: 'PGK',
    currencyName: 'Kina',
    lang: ['en', 'tpi', 'ho'],
    phone_code: '+675',
  },
  PH: {
    iso3: 'PHL',
    name: 'Philippines',
    capital: 'Manila',
    currencyCode: 'PHP',
    currencyName: 'Peso',
    lang: ['en', 'tl'],
    phone_code: '+63',
  },
  PK: {
    iso3: 'PAK',
    name: 'Pakistan',
    capital: 'Islamabad',
    currencyCode: 'PKR',
    currencyName: 'Rupee',
    lang: ['en', 'ur'],
    phone_code: '+92',
  },
  PL: {
    iso3: 'POL',
    name: 'Poland',
    capital: 'Warsaw',
    currencyCode: 'PLN',
    currencyName: 'Zloty',
    lang: ['pl'],
    phone_code: '+48',
  },
  PM: {
    iso3: 'SPM',
    name: 'Saint Pierre and Miquelon',
    capital: 'Saint-Pierre',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+508',
  },
  PN: {
    iso3: 'PCN',
    name: 'Pitcairn',
    capital: 'Adamstown',
    currencyCode: 'NZD',
    currencyName: 'Dollar',
    lang: ['en', 'pih'],
    phone_code: '+872',
  },
  PR: {
    iso3: 'PRI',
    name: 'Puerto Rico',
    capital: 'San Juan',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['es', 'en'],
    phone_code: '+1939',
  },
  PS: {
    iso3: 'PSE',
    name: 'Palestinian Territory',
    capital: 'East Jerusalem',
    currencyCode: 'ILS',
    currencyName: 'Shekel',
    lang: ['ar', 'he'],
    phone_code: '+970',
  },
  PT: {
    iso3: 'PRT',
    name: 'Portugal',
    capital: 'Lisbon',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['pt'],
    phone_code: '+351',
  },
  PW: {
    iso3: 'PLW',
    name: 'Palau',
    capital: 'Melekeok',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en', 'pau', 'ja', 'sov', 'tox'],
    phone_code: '+680',
  },
  PY: {
    iso3: 'PRY',
    name: 'Paraguay',
    capital: 'Asuncion',
    currencyCode: 'PYG',
    currencyName: 'Guarani',
    lang: ['es', 'gn'],
    phone_code: '+595',
  },
  QA: {
    iso3: 'QAT',
    name: 'Qatar',
    capital: 'Doha',
    currencyCode: 'QAR',
    currencyName: 'Rial',
    lang: ['ar'],
    phone_code: '+974',
  },
  RE: {
    iso3: 'REU',
    name: 'Reunion',
    capital: 'Saint-Denis',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+262',
  },
  RO: {
    iso3: 'ROU',
    name: 'Romania',
    capital: 'Bucharest',
    currencyCode: 'RON',
    currencyName: 'Leu',
    lang: ['ro'],
    phone_code: '+40',
  },
  RS: {
    iso3: 'SRB',
    name: 'Serbia',
    capital: 'Belgrade',
    currencyCode: 'RSD',
    currencyName: 'Dinar',
    lang: ['sr'],
    phone_code: '+381',
  },
  RU: {
    iso3: 'RUS',
    name: 'Russia',
    capital: 'Moscow',
    currencyCode: 'RUB',
    currencyName: 'Ruble',
    lang: ['ru'],
    phone_code: '+7',
  },
  RW: {
    iso3: 'RWA',
    name: 'Rwanda',
    capital: 'Kigali',
    currencyCode: 'RWF',
    currencyName: 'Franc',
    lang: ['rw', 'fr', 'en'],
    phone_code: '+250',
  },
  SA: {
    iso3: 'SAU',
    name: 'Saudi Arabia',
    capital: 'Riyadh',
    currencyCode: 'SAR',
    currencyName: 'Rial',
    lang: ['ar'],
    phone_code: '+966',
  },
  SB: {
    iso3: 'SLB',
    name: 'Solomon Islands',
    capital: 'Honiara',
    currencyCode: 'SBD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+677',
  },
  SC: {
    iso3: 'SYC',
    name: 'Seychelles',
    capital: 'Victoria',
    currencyCode: 'SCR',
    currencyName: 'Rupee',
    lang: ['fr', 'en', 'crs'],
    phone_code: '+248',
  },
  SD: {
    iso3: 'SDN',
    name: 'Sudan',
    capital: 'Khartoum',
    currencyCode: 'SDG',
    currencyName: 'Pound',
    lang: ['ar', 'en'],
    phone_code: '+249',
  },
  SS: {
    iso3: 'SSD',
    name: 'South Sudan',
    capital: 'Juba',
    currencyCode: 'SSP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+211',
  },
  SE: {
    iso3: 'SWE',
    name: 'Sweden',
    capital: 'Stockholm',
    currencyCode: 'SEK',
    currencyName: 'Krona',
    lang: ['sv'],
    phone_code: '+46',
  },
  SG: {
    iso3: 'SGP',
    name: 'Singapore',
    capital: 'Singapur',
    currencyCode: 'SGD',
    currencyName: 'Dollar',
    lang: ['en', 'ms', 'zh', 'ta'],
    phone_code: '+65',
  },
  SH: {
    iso3: 'SHN',
    name: 'Saint Helena',
    capital: 'Jamestown',
    currencyCode: 'SHP',
    currencyName: 'Pound',
    lang: ['en'],
    phone_code: '+290',
  },
  SI: {
    iso3: 'SVN',
    name: 'Slovenia',
    capital: 'Ljubljana',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['sl'],
    phone_code: '+386',
  },
  SJ: {
    iso3: 'SJM',
    name: 'Svalbard and Jan Mayen',
    capital: 'Longyearbyen',
    currencyCode: 'NOK',
    currencyName: 'Krone',
    lang: ['no'],
    phone_code: '+47',
  },
  SK: {
    iso3: 'SVK',
    name: 'Slovakia',
    capital: 'Bratislava',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['sk'],
    phone_code: '+421',
  },
  SL: {
    iso3: 'SLE',
    name: 'Sierra Leone',
    capital: 'Freetown',
    currencyCode: 'SLL',
    currencyName: 'Leone',
    lang: ['en'],
    phone_code: '+232',
  },
  SM: {
    iso3: 'SMR',
    name: 'San Marino',
    capital: 'San Marino',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['it'],
    phone_code: '+378',
  },
  SN: {
    iso3: 'SEN',
    name: 'Senegal',
    capital: 'Dakar',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+221',
  },
  SO: {
    iso3: 'SOM',
    name: 'Somalia',
    capital: 'Mogadishu',
    currencyCode: 'SOS',
    currencyName: 'Shilling',
    lang: ['so', 'ar'],
    phone_code: '+252',
  },
  SR: {
    iso3: 'SUR',
    name: 'Suriname',
    capital: 'Paramaribo',
    currencyCode: 'SRD',
    currencyName: 'Dollar',
    lang: ['nl'],
    phone_code: '+597',
  },
  ST: {
    iso3: 'STP',
    name: 'Sao Tome and Principe',
    capital: 'Sao Tome',
    currencyCode: 'STD',
    currencyName: 'Dobra',
    lang: ['pt'],
    phone_code: '+239',
  },
  SV: {
    iso3: 'SLV',
    name: 'El Salvador',
    capital: 'San Salvador',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['es'],
    phone_code: '+503',
  },
  SX: {
    iso3: 'SXM',
    name: 'Sint Maarten',
    capital: 'Philipsburg',
    currencyCode: 'ANG',
    currencyName: 'Guilder',
    lang: ['nl', 'en'],
  },
  SY: {
    iso3: 'SYR',
    name: 'Syria',
    capital: 'Damascus',
    currencyCode: 'SYP',
    currencyName: 'Pound',
    lang: ['ar'],
    phone_code: '+963',
  },
  SZ: {
    iso3: 'SWZ',
    name: 'Swaziland',
    capital: 'Mbabane',
    currencyCode: 'SZL',
    currencyName: 'Lilangeni',
    lang: ['en', 'ss'],
    phone_code: '+268',
  },
  TC: {
    iso3: 'TCA',
    name: 'Turks and Caicos Islands',
    capital: 'Cockburn Town',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1649',
  },
  TD: {
    iso3: 'TCD',
    name: 'Chad',
    capital: "N'Djamena",
    currencyCode: 'XAF',
    currencyName: 'Franc',
    lang: ['fr', 'ar'],
    phone_code: '+235',
  },
  TF: {
    iso3: 'ATF',
    name: 'French Southern Territories',
    capital: 'Port-aux-Francais',
    currencyCode: 'EUR',
    currencyName: 'Euro  ',
    lang: ['fr'],
    phone_code: '+262',
  },
  TG: {
    iso3: 'TGO',
    name: 'Togo',
    capital: 'Lome',
    currencyCode: 'XOF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+228',
  },
  TH: {
    iso3: 'THA',
    name: 'Thailand',
    capital: 'Bangkok',
    currencyCode: 'THB',
    currencyName: 'Baht',
    lang: ['th'],
    phone_code: '+66',
  },
  TJ: {
    iso3: 'TJK',
    name: 'Tajikistan',
    capital: 'Dushanbe',
    currencyCode: 'TJS',
    currencyName: 'Somoni',
    lang: ['tg', 'ru'],
    phone_code: '+992',
  },
  TK: {
    iso3: 'TKL',
    name: 'Tokelau',
    capital: '',
    currencyCode: 'NZD',
    currencyName: 'Dollar',
    lang: ['tkl', 'en', 'sm'],
    phone_code: '+690',
  },
  TL: {
    iso3: 'TLS',
    name: 'East Timor',
    capital: 'Dili',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['pt', 'tet'],
    phone_code: '+670',
  },
  TM: {
    iso3: 'TKM',
    name: 'Turkmenistan',
    capital: 'Ashgabat',
    currencyCode: 'TMT',
    currencyName: 'Manat',
    lang: ['tk'],
    phone_code: '+993',
  },
  TN: {
    iso3: 'TUN',
    name: 'Tunisia',
    capital: 'Tunis',
    currencyCode: 'TND',
    currencyName: 'Dinar',
    lang: ['ar'],
    phone_code: '+216',
  },
  TO: {
    iso3: 'TON',
    name: 'Tonga',
    capital: "Nuku'alofa",
    currencyCode: 'TOP',
    currencyName: "Pa'anga",
    lang: ['en'],
    phone_code: '+676',
  },
  TR: {
    iso3: 'TUR',
    name: 'Turkey',
    capital: 'Ankara',
    currencyCode: 'TRY',
    currencyName: 'Lira',
    lang: ['tr'],
    phone_code: '+90',
  },
  TT: {
    iso3: 'TTO',
    name: 'Trinidad and Tobago',
    capital: 'Port of Spain',
    currencyCode: 'TTD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1868',
  },
  TV: {
    iso3: 'TUV',
    name: 'Tuvalu',
    capital: 'Funafuti',
    currencyCode: 'AUD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+688',
  },
  TW: {
    iso3: 'TWN',
    name: 'Taiwan',
    capital: 'Taipei',
    currencyCode: 'TWD',
    currencyName: 'Dollar',
    lang: ['zh'],
    phone_code: '+886',
  },
  TZ: {
    iso3: 'TZA',
    name: 'Tanzania',
    capital: 'Dodoma',
    currencyCode: 'TZS',
    currencyName: 'Shilling',
    lang: ['sw', 'en'],
    phone_code: '+255',
  },
  UA: {
    iso3: 'UKR',
    name: 'Ukraine',
    capital: 'Kiev',
    currencyCode: 'UAH',
    currencyName: 'Hryvnia',
    lang: ['uk'],
    phone_code: '+380',
  },
  UG: {
    iso3: 'UGA',
    name: 'Uganda',
    capital: 'Kampala',
    currencyCode: 'UGX',
    currencyName: 'Shilling',
    lang: ['en', 'sw'],
    phone_code: '+256',
  },
  UM: {
    iso3: 'UMI',
    name: 'United States Minor Outlying Islands',
    capital: '',
    currencyCode: 'USD',
    currencyName: 'Dollar ',
    lang: ['en'],
    phone_code: '',
  },
  US: {
    iso3: 'USA',
    name: 'United States',
    capital: 'Washington',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1',
  },
  UY: {
    iso3: 'URY',
    name: 'Uruguay',
    capital: 'Montevideo',
    currencyCode: 'UYU',
    currencyName: 'Peso',
    lang: ['es'],
    phone_code: '+598',
  },
  UZ: {
    iso3: 'UZB',
    name: 'Uzbekistan',
    capital: 'Tashkent',
    currencyCode: 'UZS',
    currencyName: 'Som',
    lang: ['uz', 'kaa'],
    phone_code: '+998',
  },
  VA: {
    iso3: 'VAT',
    name: 'Vatican',
    capital: 'Vatican City',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['it'],
    phone_code: '+379',
  },
  VC: {
    iso3: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    capital: 'Kingstown',
    currencyCode: 'XCD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1784',
  },
  VE: {
    iso3: 'VEN',
    name: 'Venezuela',
    capital: 'Caracas',
    currencyCode: 'VEF',
    currencyName: 'Bolivar',
    lang: ['es'],
    phone_code: '+58',
  },
  VG: {
    iso3: 'VGB',
    name: 'British Virgin Islands',
    capital: 'Road Town',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1284',
  },
  VI: {
    iso3: 'VIR',
    name: 'U.S. Virgin Islands',
    capital: 'Charlotte Amalie',
    currencyCode: 'USD',
    currencyName: 'Dollar',
    lang: ['en'],
    phone_code: '+1340',
  },
  VN: {
    iso3: 'VNM',
    name: 'Vietnam',
    capital: 'Hanoi',
    currencyCode: 'VND',
    currencyName: 'Dong',
    lang: ['vi'],
    phone_code: '+84',
  },
  VU: {
    iso3: 'VUT',
    name: 'Vanuatu',
    capital: 'Port Vila',
    currencyCode: 'VUV',
    currencyName: 'Vatu',
    lang: ['bi', 'en', 'fr'],
    phone_code: '+678',
  },
  WF: {
    iso3: 'WLF',
    name: 'Wallis and Futuna',
    capital: 'Mata Utu',
    currencyCode: 'XPF',
    currencyName: 'Franc',
    lang: ['fr'],
    phone_code: '+681',
  },
  WS: {
    iso3: 'WSM',
    name: 'Samoa',
    capital: 'Apia',
    currencyCode: 'WST',
    currencyName: 'Tala',
    lang: ['sm', 'en'],
    phone_code: '+685',
  },
  YE: {
    iso3: 'YEM',
    name: 'Yemen',
    capital: 'Sanaa',
    currencyCode: 'YER',
    currencyName: 'Rial',
    lang: ['ar'],
    phone_code: '+967',
  },
  YT: {
    iso3: 'MYT',
    name: 'Mayotte',
    capital: 'Mamoudzou',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    lang: ['fr'],
    phone_code: '+262',
  },
  ZA: {
    iso3: 'ZAF',
    name: 'South Africa',
    capital: 'Pretoria',
    currencyCode: 'ZAR',
    currencyName: 'Rand',
    lang: ['af', 'zu', 'xh'],
    phone_code: '+27',
  },
  ZM: {
    iso3: 'ZMB',
    name: 'Zambia',
    capital: 'Lusaka',
    currencyCode: 'ZMK',
    currencyName: 'Kwacha',
    lang: ['en'],
    phone_code: '+260',
  },
  ZW: {
    iso3: 'ZWE',
    name: 'Zimbabwe',
    capital: 'Harare',
    currencyCode: 'ZWL',
    currencyName: 'Dollar',
    lang: ['en', 'sn', 'nd'],
    phone_code: '+263',
  },
  CS: {
    iso3: 'SCG',
    name: 'Serbia and Montenegro',
    capital: 'Belgrade',
    currencyCode: 'RSD',
    lang: ['sr'],
    currencyName: 'Dinar',
    phone_code: '+381',
  },
  AN: {
    iso3: 'ANT',
    name: 'Netherlands Antilles',
    capital: 'Willemstad',
    currencyCode: 'ANG',
    currencyName: 'Guilder',
    lang: ['en', 'nl'],
    phone_code: '+599',
  },
};

export const Langs: any = {
  ca: 'Catalan',
  ar: 'Arabic',
  fa: 'Persian',
  en: 'English',
  sq: 'Albanian',
  hy: 'Armenian',
  pt: 'Portuguese',
  es: 'Spanish',
  de: 'German',
  nl: 'Dutch',
  sv: 'Swedish',
  az: 'Azerbaijani',
  bs: 'Bosnian',
  bn: 'Bangla',
  fr: 'French',
  bg: 'Bulgarian',
  ms: 'Malay',
  dz: 'dz',
  no: 'Norwegian',
  be: 'Belarusian',
  zh: 'Chinese',
  el: 'Greek',
  cs: 'Czech',
  da: 'Danish',
  et: 'Estonian',
  ti: 'Tigrinya',
  am: 'Amharic',
  fi: 'Finnish',
  fo: 'Faroese',
  ka: 'Georgian',
  kl: 'kl',
  hr: 'Croatian',
  hu: 'Hungarian',
  id: 'Indonesian',
  he: 'Hebrew',
  hi: 'Hindi',
  is: 'Icelandic',
  it: 'Italian',
  ja: 'Japanese',
  sw: 'Swahili',
  ky: 'Kyrgyz',
  km: 'Khmer',
  bnt: 'bnt',
  ko: 'Korean',
  kk: 'Kazakh',
  lo: 'Lao',
  si: 'Sinhala',
  lt: 'Lithuanian',
  lb: 'Luxembourgish',
  lv: 'Latvian',
  ru: 'Russian',
  sr: 'Serbian',
  mg: 'Malagasy',
  mk: 'Macedonian',
  my: 'Burmese',
  mn: 'Mongolian',
  ch: 'ch',
  mt: 'Maltese',
  mfe: 'Morisyen',
  dv: 'dv',
  nb: 'Norwegian Bokmål',
  ne: 'Nepali',
  na: 'na',
  niu: 'niu',
  mi: 'Māori',
  pl: 'Polish',
  ro: 'Romanian',
  rw: 'Kinyarwanda',
  sl: 'Slovenian',
  sk: 'Slovak',
  so: 'Somali',
  th: 'Thai',
  tg: 'Tajik',
  tkl: 'tkl',
  tk: 'Turkmen',
  tr: 'Turkish',
  uk: 'Ukrainian',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  bi: 'bi',
  sm: 'Samoan',
  af: 'Afrikaans',
};

export const Currencies: any = {
  ALL: {
    name: 'Albanian Lek',
    symbol: 'LEK',
  },
  XCD: {
    name: 'East Caribbean Dollar',
    symbol: '$',
  },
  EUR: {
    name: 'Euro',
    symbol: '€',
  },
  BBD: {
    name: 'Barbadian Dollar',
    symbol: '$',
  },
  BTN: {
    name: 'Bhutanese Ngultrum',
    symbol: 'BTN',
  },
  BND: {
    name: 'Brunei Dollar',
    symbol: '$',
  },
  XAF: {
    name: 'Central African CFA Franc',
    symbol: 'XAF',
  },
  CUP: {
    name: 'Cuban Peso',
    symbol: '$',
  },
  USD: {
    name: 'United States Dollar',
    symbol: '$',
  },
  FKP: {
    name: 'Falkland Islands Pound',
    symbol: '£',
  },
  GIP: {
    name: 'Gibraltar Pound',
    symbol: '£',
  },
  HUF: {
    name: 'Hungarian Forint',
    symbol: 'FT',
  },
  IRR: {
    name: 'Iranian Rial',
    symbol: '﷼',
  },
  JMD: {
    name: 'Jamaican Dollar',
    symbol: 'J$',
  },
  AUD: {
    name: 'Australian Dollar',
    symbol: '$',
  },
  LAK: {
    name: 'Lao Kip',
    symbol: '₭',
  },
  LYD: {
    name: 'Libyan Dinar',
    symbol: 'LYD',
  },
  MKD: {
    name: 'Macedonian Denar',
    symbol: 'ДЕН',
  },
  XOF: {
    name: 'West African CFA Franc',
    symbol: 'XOF',
  },
  NZD: {
    name: 'New Zealand Dollar',
    symbol: '$',
  },
  OMR: {
    name: 'Omani Rial',
    symbol: '﷼',
  },
  PGK: {
    name: 'Papua New Guinean Kina',
    symbol: 'PGK',
  },
  RWF: {
    name: 'Rwandan Franc',
    symbol: 'RWF',
  },
  WST: {
    name: 'Samoan Tala',
    symbol: 'WST',
  },
  RSD: {
    name: 'Serbian Dinar',
    symbol: 'ДИН.',
  },
  SEK: {
    name: 'Swedish Krona',
    symbol: 'KR',
  },
  TZS: {
    name: 'Tanzanian Shilling',
    symbol: 'TSH',
  },
  AMD: {
    name: 'Armenian Dram',
    symbol: 'AMD',
  },
  BSD: {
    name: 'Bahamian Dollar',
    symbol: '$',
  },
  BAM: {
    name: 'Bosnia And Herzegovina Konvertibilna Marka',
    symbol: 'KM',
  },
  CVE: {
    name: 'Cape Verdean Escudo',
    symbol: 'CVE',
  },
  CNY: {
    name: 'Chinese Yuan',
    symbol: '¥',
  },
  CRC: {
    name: 'Costa Rican Colon',
    symbol: '₡',
  },
  CZK: {
    name: 'Czech Koruna',
    symbol: 'KČ',
  },
  ERN: {
    name: 'Eritrean Nakfa',
    symbol: 'ERN',
  },
  GEL: {
    name: 'Georgian Lari',
    symbol: 'GEL',
  },
  HTG: {
    name: 'Haitian Gourde',
    symbol: 'HTG',
  },
  INR: {
    name: 'Indian Rupee',
    symbol: '₹',
  },
  JOD: {
    name: 'Jordanian Dinar',
    symbol: 'JOD',
  },
  KRW: {
    name: 'South Korean Won',
    symbol: '₩',
  },
  LBP: {
    name: 'Lebanese Lira',
    symbol: '£',
  },
  MWK: {
    name: 'Malawian Kwacha',
    symbol: 'MWK',
  },
  MRO: {
    name: 'Mauritanian Ouguiya',
    symbol: 'MRO',
  },
  MZN: {
    name: 'Mozambican Metical',
    symbol: 'MZN',
  },
  ANG: {
    name: 'Netherlands Antillean Gulden',
    symbol: 'Ƒ',
  },
  PEN: {
    name: 'Peruvian Nuevo Sol',
    symbol: 'S/.',
  },
  QAR: {
    name: 'Qatari Riyal',
    symbol: '﷼',
  },
  STD: {
    name: 'Sao Tome And Principe Dobra',
    symbol: 'STD',
  },
  SLL: {
    name: 'Sierra Leonean Leone',
    symbol: 'SLL',
  },
  SOS: {
    name: 'Somali Shilling',
    symbol: 'S',
  },
  SDG: {
    name: 'Sudanese Pound',
    symbol: 'SDG',
  },
  SYP: {
    name: 'Syrian Pound',
    symbol: '£',
  },
  AOA: {
    name: 'Angolan Kwanza',
    symbol: 'AOA',
  },
  AWG: {
    name: 'Aruban Florin',
    symbol: 'Ƒ',
  },
  BHD: {
    name: 'Bahraini Dinar',
    symbol: 'BHD',
  },
  BZD: {
    name: 'Belize Dollar',
    symbol: 'BZ$',
  },
  BWP: {
    name: 'Botswana Pula',
    symbol: 'P',
  },
  BIF: {
    name: 'Burundi Franc',
    symbol: 'BIF',
  },
  KYD: {
    name: 'Cayman Islands Dollar',
    symbol: '$',
  },
  COP: {
    name: 'Colombian Peso',
    symbol: '$',
  },
  DKK: {
    name: 'Danish Krone',
    symbol: 'KR',
  },
  GTQ: {
    name: 'Guatemalan Quetzal',
    symbol: 'Q',
  },
  HNL: {
    name: 'Honduran Lempira',
    symbol: 'L',
  },
  IDR: {
    name: 'Indonesian Rupiah',
    symbol: 'RP',
  },
  ILS: {
    name: 'Israeli New Sheqel',
    symbol: '₪',
  },
  KZT: {
    name: 'Kazakhstani Tenge',
    symbol: 'ЛВ',
  },
  KWD: {
    name: 'Kuwaiti Dinar',
    symbol: 'KWD',
  },
  LSL: {
    name: 'Lesotho Loti',
    symbol: 'LSL',
  },
  MYR: {
    name: 'Malaysian Ringgit',
    symbol: 'RM',
  },
  MUR: {
    name: 'Mauritian Rupee',
    symbol: '₨',
  },
  MNT: {
    name: 'Mongolian Tugrik',
    symbol: '₮',
  },
  MMK: {
    name: 'Myanma Kyat',
    symbol: 'MMK',
  },
  NGN: {
    name: 'Nigerian Naira',
    symbol: '₦',
  },
  PAB: {
    name: 'Panamanian Balboa',
    symbol: 'B/.',
  },
  PHP: {
    name: 'Philippine Peso',
    symbol: '₱',
  },
  RON: {
    name: 'Romanian Leu',
    symbol: 'LEI',
  },
  SAR: {
    name: 'Saudi Riyal',
    symbol: '﷼',
  },
  SGD: {
    name: 'Singapore Dollar',
    symbol: '$',
  },
  ZAR: {
    name: 'South African Rand',
    symbol: 'R',
  },
  SRD: {
    name: 'Surinamese Dollar',
    symbol: '$',
  },
  TWD: {
    name: 'New Taiwan Dollar',
    symbol: 'NT$',
  },
  TOP: {
    name: 'Paanga',
    symbol: 'TOP',
  },
  VEF: {
    name: 'Venezuelan Bolivar',
    symbol: 'VEF',
  },
  DZD: {
    name: 'Algerian Dinar',
    symbol: 'DZD',
  },
  ARS: {
    name: 'Argentine Peso',
    symbol: '$',
  },
  AZN: {
    name: 'Azerbaijani Manat',
    symbol: 'MAH',
  },
  BYR: {
    name: 'Belarusian Ruble',
    symbol: 'P.',
  },
  BOB: {
    name: 'Bolivian Boliviano',
    symbol: '$B',
  },
  BGN: {
    name: 'Bulgarian Lev',
    symbol: 'ЛВ',
  },
  CAD: {
    name: 'Canadian Dollar',
    symbol: '$',
  },
  CLP: {
    name: 'Chilean Peso',
    symbol: '$',
  },
  CDF: {
    name: 'Congolese Franc',
    symbol: 'CDF',
  },
  DOP: {
    name: 'Dominican Peso',
    symbol: 'RD$',
  },
  FJD: {
    name: 'Fijian Dollar',
    symbol: '$',
  },
  GMD: {
    name: 'Gambian Dalasi',
    symbol: 'GMD',
  },
  GYD: {
    name: 'Guyanese Dollar',
    symbol: '$',
  },
  ISK: {
    name: 'Icelandic Króna',
    symbol: 'KR',
  },
  IQD: {
    name: 'Iraqi Dinar',
    symbol: 'IQD',
  },
  JPY: {
    name: 'Japanese Yen',
    symbol: '¥',
  },
  KPW: {
    name: 'North Korean Won',
    symbol: '₩',
  },
  LVL: {
    name: 'Latvian Lats',
    symbol: 'LS',
  },
  CHF: {
    name: 'Swiss Franc',
    symbol: 'FR.',
  },
  MGA: {
    name: 'Malagasy Ariary',
    symbol: 'MGA',
  },
  MDL: {
    name: 'Moldovan Leu',
    symbol: 'MDL',
  },
  MAD: {
    name: 'Moroccan Dirham',
    symbol: 'MAD',
  },
  NPR: {
    name: 'Nepalese Rupee',
    symbol: '₨',
  },
  NIO: {
    name: 'Nicaraguan Cordoba',
    symbol: 'C$',
  },
  PKR: {
    name: 'Pakistani Rupee',
    symbol: '₨',
  },
  PYG: {
    name: 'Paraguayan Guarani',
    symbol: 'GS',
  },
  SHP: {
    name: 'Saint Helena Pound',
    symbol: '£',
  },
  SCR: {
    name: 'Seychellois Rupee',
    symbol: '₨',
  },
  SBD: {
    name: 'Solomon Islands Dollar',
    symbol: '$',
  },
  LKR: {
    name: 'Sri Lankan Rupee',
    symbol: '₨',
  },
  THB: {
    name: 'Thai Baht',
    symbol: '฿',
  },
  TRY: {
    name: 'Turkish New Lira',
    symbol: 'TRY',
  },
  AED: {
    name: 'UAE Dirham',
    symbol: 'AED',
  },
  VUV: {
    name: 'Vanuatu Vatu',
    symbol: 'VUV',
  },
  YER: {
    name: 'Yemeni Rial',
    symbol: '﷼',
  },
  AFN: {
    name: 'Afghan Afghani',
    symbol: '؋',
  },
  BDT: {
    name: 'Bangladeshi Taka',
    symbol: '৳',
  },
  BRL: {
    name: 'Brazilian Real',
    symbol: 'R$',
  },
  KHR: {
    name: 'Cambodian Riel',
    symbol: '៛',
  },
  KMF: {
    name: 'Comorian Franc',
    symbol: 'KMF',
  },
  HRK: {
    name: 'Croatian Kuna',
    symbol: 'KN',
  },
  DJF: {
    name: 'Djiboutian Franc',
    symbol: 'DJF',
  },
  EGP: {
    name: 'Egyptian Pound',
    symbol: '£',
  },
  ETB: {
    name: 'Ethiopian Birr',
    symbol: 'ETB',
  },
  XPF: {
    name: 'CFP Franc',
    symbol: 'XPF',
  },
  GHS: {
    name: 'Ghanaian Cedi',
    symbol: 'GHS',
  },
  GNF: {
    name: 'Guinean Franc',
    symbol: 'GNF',
  },
  HKD: {
    name: 'Hong Kong Dollar',
    symbol: '$',
  },
  XDR: {
    name: 'Special Drawing Rights',
    symbol: 'XDR',
  },
  KES: {
    name: 'Kenyan Shilling',
    symbol: 'KSH',
  },
  KGS: {
    name: 'Kyrgyzstani Som',
    symbol: 'ЛВ',
  },
  LRD: {
    name: 'Liberian Dollar',
    symbol: '$',
  },
  MOP: {
    name: 'Macanese Pataca',
    symbol: 'MOP',
  },
  MVR: {
    name: 'Maldivian Rufiyaa',
    symbol: 'MVR',
  },
  MXN: {
    name: 'Mexican Peso',
    symbol: '$',
  },
  NAD: {
    name: 'Namibian Dollar',
    symbol: '$',
  },
  NOK: {
    name: 'Norwegian Krone',
    symbol: 'KR',
  },
  PLN: {
    name: 'Polish Zloty',
    symbol: 'ZŁ',
  },
  RUB: {
    name: 'Russian Ruble',
    symbol: 'РУБ',
  },
  SZL: {
    name: 'Swazi Lilangeni',
    symbol: 'SZL',
  },
  TJS: {
    name: 'Tajikistani Somoni',
    symbol: 'TJS',
  },
  TTD: {
    name: 'Trinidad and Tobago Dollar',
    symbol: 'TT$',
  },
  UGX: {
    name: 'Ugandan Shilling',
    symbol: 'USH',
  },
  UYU: {
    name: 'Uruguayan Peso',
    symbol: '$U',
  },
  VND: {
    name: 'Vietnamese Dong',
    symbol: '₫',
  },
  TND: {
    name: 'Tunisian Dinar',
    symbol: 'TND',
  },
  UAH: {
    name: 'Ukrainian Hryvnia',
    symbol: '₴',
  },
  UZS: {
    name: 'Uzbekistani Som',
    symbol: 'ЛВ',
  },
  TMT: {
    name: 'Turkmenistan Manat',
    symbol: 'TMT',
  },
  GBP: {
    name: 'British Pound',
    symbol: '£',
  },
  ZMW: {
    name: 'Zambian Kwacha',
    symbol: 'ZMW',
  },
  BYN: {
    name: 'New Belarusian Ruble',
    symbol: 'P.',
  },
  BMD: {
    name: 'Bermudan Dollar',
    symbol: 'BMD',
  },
  GGP: {
    name: 'Guernsey Pound',
    symbol: 'GGP',
  },
  CLF: {
    name: 'Chilean Unit Of Account',
    symbol: 'CLF',
  },
  CUC: {
    name: 'Cuban Convertible Peso',
    symbol: 'CUC',
  },
  IMP: {
    name: 'Manx pound',
    symbol: 'IMP',
  },
  JEP: {
    name: 'Jersey Pound',
    symbol: 'JEP',
  },
  SVC: {
    name: 'Salvadoran Colón',
    symbol: 'SVC',
  },
  ZMK: {
    name: 'Old Zambian Kwacha',
    symbol: 'ZMK',
  },
  XAG: {
    name: 'Silver (troy ounce)',
    symbol: 'XAG',
  },
  ZWL: {
    name: 'Zimbabwean Dollar',
    symbol: 'ZWL',
  },
};
